package Package1;
// Generated Apr 11, 2018 8:53:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private int id;
     private String model;
     private String name;
     private int price;
     private String availibility;
     private Set<Bookedcars> bookedcarses = new HashSet<Bookedcars>(0);

    public Cars() {
    }

	
    public Cars(int id, String model, String name, int price, String availibility) {
        this.id = id;
        this.model = model;
        this.name = name;
        this.price = price;
        this.availibility = availibility;
    }
    public Cars(int id, String model, String name, int price, String availibility, Set<Bookedcars> bookedcarses) {
       this.id = id;
       this.model = model;
       this.name = name;
       this.price = price;
       this.availibility = availibility;
       this.bookedcarses = bookedcarses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getAvailibility() {
        return this.availibility;
    }
    
    public void setAvailibility(String availibility) {
        this.availibility = availibility;
    }
    public Set<Bookedcars> getBookedcarses() {
        return this.bookedcarses;
    }
    
    public void setBookedcarses(Set<Bookedcars> bookedcarses) {
        this.bookedcarses = bookedcarses;
    }




}


