package Package1;
// Generated Apr 11, 2018 8:53:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String username;
     private String password;
     private Set<Bookedcars> bookedcarses = new HashSet<Bookedcars>(0);

    public Users() {
    }

	
    public Users(int userId, String username, String password) {
        this.userId = userId;
        this.username = username;
        this.password = password;
    }
    public Users(int userId, String username, String password, Set<Bookedcars> bookedcarses) {
       this.userId = userId;
       this.username = username;
       this.password = password;
       this.bookedcarses = bookedcarses;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Bookedcars> getBookedcarses() {
        return this.bookedcarses;
    }
    
    public void setBookedcarses(Set<Bookedcars> bookedcarses) {
        this.bookedcarses = bookedcarses;
    }




}


